export default [
    'Yaswanth auditor fees',
    'BWSSB Water bill',
    'Diesel Purchased',
    'Bescom electricity bill payment',
    'Housekeeping Salary (Hyrunnisa / Sunanda)',
    'Security Salary',
    'Garden Maintenance / Work',
    'Garbage Collection Vendor (Hasirudala)/BBMP',
    'Borewell And Motor Maintenance/Repair',
    'Annual Bonus',
    'Lift Maintenance (Johnson)',
    'HK items (bleaching powder,garbage bin etc)',
    'Health Club Maintenance',
    'EB / Electrical / Plumbing Repairs',
    'Apartment repairs related - Concrete floor - Sivaji',
    'Apartment Safety - Fire Extiguisher',
    'CCTV / Intercomm',
    'Misc expenses - Cash Paid for unbilled services',
    'Apartment developments - Stationary/books/pens/papers/clips/file/folders purchased',
    'Apartment work done By Security and Others',
    'Septic Tank Repair / Cleaning',
    'Water Tank/Tanks Cleaning',
    'Generator Maintenance and Repair',
    'Festival/Holiday Celebration',
    'Drinking Water for Employees',
    'BAF Subscription Charges',
];
