const CAT_INDEX: { [month: string]: number } = {
    'Audit Fees': 1,
    BWSSB: 2,
    Diesel: 3,
    Bescom: 4,
    'House Keeping Salary': 5,
    Security: 6,
    'Garden Maintenance': 7,
    'Garbage Collection Vendor (Hasirudala)/BBMP': 8,
    'Borewell And Motor Maintenance': 9,
    'Annual Bonus': 10,
    'Lift Maintenance (Johnson)': 11,
    'HK Items Purchased': 12,
    'Health Club Maintenance': 13,
    'Electrical / Plumbing Repairs': 14,
    'Apartment repairs related': 15,
    'Apartment Safety': 16,
    'CCTV / Intercomm': 17,
    'Misc expenses': 18,
    'Apartment developments': 19,
    'Apartment Work By Security and Others': 20,
    'Septic Tank Repairs / Cleaning': 21,
    'Water Tanks Cleaning': 22,
    'Generator Maintenance and Repair': 23,
    'SMS Charges/Cheque book (Vijaya Bank)': 24,
    'Festival/Holiday Celebration': 25,
    'Drinking Water for Employees': 26,
    'BAF Subscription Charges': 27,
    'Maintenance Collection': 30,
    'Income Tax Refund': 31,
    'Other Income': 32,
    'Interest on account': 33,
    'Fine / Extra Payment Received': 34,
    'Corpus Fund': 35,
    'Tenant Deposit from the Owners': 36,
    'FD Deposit': 37,
    'Deposit to RD account': 38,
};

export default CAT_INDEX;
