export enum TransCategory {
    'Audit Fees' = 'Audit Fees',
    'BWSSB' = 'BWSSB',
    'Diesel' = 'Diesel',
    'Bescom' = 'Bescom',
    'House Keeping Salary' = 'House Keeping Salary',
    'Security' = 'Security',
    'Garden Maintenance' = 'Garden Maintenance',
    'Garbage Collection Vendor / BBMP' = 'Garbage Collection Vendor / BBMP',
    'Borewell And Motor Maintenance' = 'Borewell And Motor Maintenance',
    'Annual Bonus' = 'Annual Bonus',
    'Lift Maintenance' = 'Lift Maintenance',
    'HK Items Purchased' = 'HK Items Purchased',
    'Health Club Maintenance' = 'Health Club Maintenance',
    'Electrical / Plumbing Repairs' = 'Electrical / Plumbing Repairs',
    'Apartment repairs related' = 'Apartment repairs related',
    'Apartment Painting' = 'Apartment Painting',
    'CCTV / Intercomm' = 'CCTV / Intercomm',
    'Misc expenses' = 'Misc expenses',
    'Apartment developments' = 'Apartment developments',
    'Apartment Work By Security and Others' = 'Apartment Work By Security and Others',
    'Septic Tank Repairs / Cleaning' = 'Septic Tank Repairs / Cleaning',
    'Water Tanks Cleaning' = 'Water Tanks Cleaning',
    'Generator Maintenance and Repair' = 'Generator Maintenance and Repair',
    'Savings Bank SMS Charges/Cheque book' = 'Savings Bank SMS Charges/Cheque book',
    'Festival/Holiday Celebration' = 'Festival/Holiday Celebration',
    'Drinking Water for Employees' = 'Drinking Water for Employees',
    'BAF Subscription Charges' = 'BAF Subscription Charges',
    'Maintenance Collection' = 'Maintenance Collection',
    'Income Tax Refund' = 'Income Tax Refund',
    'Other Income' = 'Other Income',
    'Interest on account' = 'Interest on account',
    'Fine / Extra Payment Received' = 'Fine / Extra Payment Received',
    'Corpus Fund' = 'Corpus Fund',
    'Tenant Deposit from the Owners' = 'Tenant Deposit from the Owners',
    'FD Deposit' = 'FD Deposit',
}
export default { TransCategory };
