# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
    - run: npm run build --if-present
    # - run: npm test
    - name: Deploy to GitHub Pages
      if: success()
      run: |
        # Configure git
        git config --global user.name "akhadir"
        git config --global user.email "abk0680@yahoo.com"

        # Initialize a new repository in the build directory
        cd build
        git init

        # Add and commit all files
        git add .
        git commit -m "Deploy to GitHub Pages"

        # Force push to the master branch of the repository
        git push --force "https://x-access-token:${{ secrets.KHADIR_GITHUB_PAGES_ACCESS_TOKEN }}@github.com/akhadir/akhadir.github.io.git" master
